### ISSUE TITLE
Помагите пажалуйста

### ISSUE THREAD

**Issue by Markushik** [alexey-goloburdin/botanim-bot#7]
Алексей, я тут посмотрел ваш 9-ти часовой стрим и у меня возникло парочку вопросов... 

1) А вы библиотеки по количеству звездочек выбираете? Или по количеству ишьюсов? Или по количеству и того и другого? 
2) А документации к библиотекам вы как ищите? 
3) А мне можно токен своим друзьям показывать? Ну чтобы они тоже могли ботом попользоваться
4) А это правда, что ТЗ нужно писать после выбора стека и бибиотек? 
5) Кстати, а в чем смысл хранения текста в отдельных файлах? 
6) Алексей, а я думал, что PostgreSQL лучше чем SQLite.
7) А почему мы не написали скрипт для обработки книг?
8) Я не понимаю, а зачем мы получаем по одному предмету и пишем в список, если можно сразу получать целый кортеж?
9) Стоит ли использовать глобалы в своих проектах? Все, что здесь написано (https://t.me/advice17/5)  это все неправда?

**Comment by Latand** [comment]
Отлично! Теперь тут есть целый 1 ишью, значит код действительно норм.

**Comment by merura** [comment]
Полностью согласен!

**Comment by alexey-goloburdin** [comment]
Ответил на стриме https://youtu.be/qnOj7IXNuME, issue закрываю

**Comment by merura** [comment]
> Ответил на стриме https://youtu.be/qnOj7IXNuME, issue закрываю

Запись будет? На какой минуте ответ?

**Comment by vvihorev** [comment]
@tshipenchko, [запись есть](https://youtu.be/qnOj7IXNuME?t=1280), ответы на 21:17

**Comment by IgorVolochay** [comment]
Открыл ветку чтобы лицезреть воочию вопросы :D
[Видос](https://www.youtube.com/watch?v=ahrWKDvXpaQ&t) с ответами на эти и другие вопросы просто топчик, Алексей, спасибо за контент
